version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tradingagents-backend
    ports:
      - "8000:8000"
    volumes:
      - ./results:/app/results
      - ./tradingagents:/app/tradingagents
      - ./cli:/app/cli
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - tradingagents-network
    restart: unless-stopped

  frontend:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    container_name: tradingagents-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - tradingagents-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: tradingagents-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - tradingagents-network
    restart: unless-stopped

networks:
  tradingagents-network:
    driver: bridge

volumes:
  results:
    driver: local
