services:
  web:
    build: .
    container_name: tradingagents-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-8080}:8000"
    volumes:
      - data:/app/data
      - results:/app/results
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  data:
  results:
