name: Deploy to Remote Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
        run: |
          if [ -z "$SSH_PRIVATE_KEY" ]; then
            echo "DEPLOY_SSH_KEY secret is not set" >&2
            exit 1
          fi
          HOST=${SSH_HOST:-124.223.193.139}
          install -m 700 -d ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy application
        env:
          REMOTE_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_SSH_USER }}
          REMOTE_DIR: ${{ vars.DEPLOY_REMOTE_DIR }}
          SSH_KEY_PATH: /home/runner/.ssh/id_rsa
        run: |
          HOST=${REMOTE_HOST:-124.223.193.139}
          USER=${REMOTE_USER:-ubuntu}
          DIR=${REMOTE_DIR:-/opt/tradingagents}
          export REMOTE_HOST="$HOST"
          export REMOTE_USER="$USER"
          export REMOTE_DIR="$DIR"
          export SSH_KEY="$SSH_KEY_PATH"
          bash deploy/deploy.sh
